### ISSUE TITLE
I have some bug, i think it`s problem with my android

### ISSUE THREAD

**Issue by vherasymenko** [anteo/torrent2http#5]
I have installed Kodi on android tv box (china) and plugin TorrenterV2. And when in settings i set default program for opening torrent links (torrent2http) i have this error. Maybe you can help me with this problem.

17:23:08 T:1864967344   DEBUG: [torrent2http] Logging thread started.
17:23:08 T:1864967344   DEBUG: [torrent2http] Stopping logging thread...
17:23:08 T:1864967344   DEBUG: [torrent2http] Logging thread finished.
17:23:08 T:1904747384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'torrent2http.error.Error'>
                                            Error Contents: Can't start torrent2http: OSError(13, 'Permission denied')
                                            Traceback (most recent call last):
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/default.py", line 41, in <module>
                                                core.executeAction(params)
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Core.py", line 1108, in executeAction
                                                getattr(self, get("action"))(params)
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Core.py", line 1479, in openTorrent
                                                for filedict in torrent.getContentList():
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Downloader.py", line 87, in getContentList
                                                return self.player.getContentList()
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Anteoloader.py", line 155, in getContentList
                                                self.engine.start()
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.torrent2http/lib/torrent2http/engine.py", line 309, in start
                                                raise Error("Can't start torrent2http: %r" % e, Error.POPEN_ERROR)
                                            Error: Can't start torrent2http: OSError(13, 'Permission denied')
                                            -->End of Python script error report<--

**Comment by beckss1** [comment]
Hi.,
I have same problem and wait for resolving it.
Any updates?
Thanks beckss......
